#Physics Parameters

#Simulation calculation rate 
/updatePhysics/simRate: 250

#Simulation time-step
/updatePhysics/deltaT: 0.004

# realTimeFactor = simRate * deltaT
# For real time simulation simRate * deltaT = 1

#Gazebo wolrd Initial State
/updatePhysics/paused: 0  # 1 for paused, 0 for not paused
